# **Pandas en Python:**
 Esencial para análisis de datos. Ofrece una interfaz similar a Excel, pero más poderosa, facilitando manipulación, análisis y visualización de datos estructurados.


### **Importar librería**

In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### **Carga de Datos**

In [4]:
# CARGA DE DATOS
df = pd.read_csv("/content/drive/MyDrive/CARLOS III 2023 2024/Colab Notebooks/Sistemas Big Data/dataset.csv") # Por defecto detecta las columnas por el encabezado del archivo
# Puedo especificar algunos parametros adicionales como por ejemplo una columna como indice
# pd.read_csv("./dataset.csv", index_col = "id")

### **Asignar la columna Id como índice**

In [5]:
# Puedo especificar algunos parametros adicionales como por ejemplo una columna como indice
df =pd.read_csv(("/content/drive/MyDrive/CARLOS III 2023 2024/Colab Notebooks/Sistemas Big Data/dataset.csv"), index_col = "id")


### **Mostrar la cabecera y primeras 8 filas**

In [6]:
df.head(8)

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129

### **Mostrar las ultimas 8 filas**

In [7]:
df.tail(8)

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378
183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

### **Proporciona Estadísticas Descriptivas**
 que resumen la tendencia central, la dispersión y la forma de la distribución de un conjunto de datos, excluyendo los valores NaN (Not a Number)

In [8]:
df.describe()

        favorites    retweets   mentions   followers    followees
count   26.000000   26.000000  26.000000   26.000000    27.000000
mean   280.538462   80.000000  15.423077  352.807692  1190.185185
std    153.377242   40.303846   9.596554  375.319493  1965.735995
min     23.000000   21.000000   1.000000   12.000000   129.000000
25%    139.250000   45.500000   8.250000   21.000000   258.000000
50%    305.500000   79.000000  16.000000  332.000000   351.000000
75%    422.500000  110.750000  23.500000  389.000000  1822.000000
max    500.000000  146.000000  29.000000  982.000000  9918.000000

### **Proporciona Estadísticas sobre columnas categóricas o de texto**
( número de valores únicos, el valor más frecuente y la frecuencia del valor más común)

In [9]:
df.describe(include='all')

,full_text,favorites,retweets,mentions,country,user,followers,followees
count,27,26.000000,26.000000,26.000000,27,27,26.000000,27.000000
unique,27,NaN,NaN,NaN,3,7,NaN,NaN
top,Flying home to run down from the power to comi...,NaN,NaN,NaN,BRASIL,mateusmartins,NaN,NaN
freq,1,NaN,NaN,NaN,11,5,NaN,NaN
mean,NaN,280.538462,80.000000,15.423077,NaN,NaN,352.807692,1190.185185
std,NaN,153.377242,40.303846,9.596554,NaN,NaN,375.319493,1965.735995
min,NaN,23.000000,21.000000,1.000000,NaN,NaN,12.000000,129.000000
25%,NaN,139.250000,45.500000,8.250000,NaN,NaN,21.000000,258.000000
50%,NaN,305.500000,79.000000,16.000000,NaN,NaN,332.000000,351.000000
75%,NaN,422.500000,110.750000,23.500000,NaN,NaN,389.000000,1822.000000
max,NaN,500.000000,146.000000,29.000000,NaN,NaN,982.000000,9918.000000

### **Proporciona los nombres de todas las columnas en el DataFrame como un objeto Index de pandas.**

In [10]:
df.columns
# columnas = df.columns.tolist()
# for item in columnas:
#   print(item)

Index(['full_text', 'favorites', 'retweets', 'mentions', 'country', 'user',
       'followers', 'followees'],
      dtype='object')

#### **Quitar filas con elemenos NaN.**

In [11]:
df_filtrado =  df.dropna()
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258





#### **Llenar los valores NaN con un valor por defecto.**

In [12]:
df_filtrado_con_valores_por_defecto = df.fillna(0)
df_filtrado_con_valores_por_defecto.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,0.0,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

#### **Llenar los valores de una columna que contenga NaN con un valor por defecto.**

In [13]:
df_filtrado_con_valores_por_defecto_en_columna = df.fillna({"retweets" : 0,"mentions" : -1})
df_filtrado_con_valores_por_defecto_en_columna.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,-1.0,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

### **Muestra el tipo de dato de cada columna en el DataFrame**

In [14]:
df_filtrado_con_valores_por_defecto_en_columna.dtypes

full_text     object
favorites    float64
retweets     float64
mentions     float64
country       object
user          object
followers    float64
followees      int64
dtype: object

### **Mostrar una columna o mas del dataframe**

In [30]:
# Muestra los datos solo de la columna favorites y limitamos a los 5 primeros
# df["favorites"][:5]
# Muestra los cinco primeros
# df["favorites"].head(5)
# Muestra los cinco ultimos
# df["favorites"].tail(5)

df[["favorites", "country"]].tail(5)

        favorites country
id
183743      432.0  BRASIL
183744      430.0  BRASIL
183745      424.0  BRASIL
183746      488.0  MEXICO
183747      318.0  BRASIL

# **Filtrado**

### **Dar las ultimas 5**

In [16]:
#dar las ultimas 5
df.iloc[-5:]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

### **Dar las primeras 5**

In [17]:
df.iloc[:5]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

### **Dar la primera fila**

In [18]:
df.iloc[0]

full_text    Flying home to run down from the power to comi...
favorites                                                 23.0
retweets                                                   NaN
mentions                                                  10.0
country                                                ECUADOR
user                                             leonardokuffo
followers                                                389.0
followees                                                  258
Name: 183721, dtype: object

#### **Filtrar por los Identificadores**

In [19]:
df.loc[[183743,183744]]
# Filtrado de Filas y Columnas

df.loc[[183743,183744], ["favorites", "country"]]

        favorites country
id
183743      432.0  BRASIL
183744      430.0  BRASIL

## **Filtrado con Condiciones**

#### Obtener los registros donde los favoritos son mayor que 400

In [20]:
# Obtener los registros donde los favoritos son mayor que 400
df[df["favorites"] > 400]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721

#### Obtener los registros donde los favoritos son mayor que 400 y metions sea mayor que 20

In [21]:
# Obtener los registros donde los favoritos son mayor que 400 y metions sea mayor que 20
df[(df["favorites"] > 400) & (df["mentions"] > 20)]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721

#### Obtener los registros que tenga en full_text "Programming"

In [22]:
# Obtener los registros que tenga en full_text "Programming"
df[df["full_text"].str.contains("Programming")]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378

# **Transformación de Datos**
Apartir de los datos existentes, crear o calcular nuevascolumnas que tengan datos transformados.

#### Transformacion de datos de una columna
Ejem : Crear una columna llamada Ganancias, que va ser el numero de retweets de cada fila multipicado de un numero aleatoria del 3 al cinco.

In [23]:
# Limpieza de Datos
df = df.fillna({"retweets" : 0,"mentions" : -1})

#Transformación de datos

import random
def cacularGanancias(retweets):
  ganancia = retweets * random.randint(3,5)
  return ganancia

df["ganancias"] = df["retweets"].apply(cacularGanancias)

df.head(10)

,full_text,favorites,retweets,mentions,country,user,followers,followees,ganancias
id,,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,ECUADOR,leonardokuffo,389.0,258,0.0
183722,Today we commemorate and MNML Case.,500.0,21.0,-1.0,BRASIL,mateusmartins,982.0,1822,84.0
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129,615.0
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378,228.0
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129,390.0
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822,350.0
183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258,160.0
183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129,250.0
183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129,246.0
183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822,460.0

#### Transformación de datos de dos o mas columnas

Ejem: Crear la columna Popular, que es dividir cuantas personas sigo y cuantas personas me siguen

In [24]:
#Transformacion de datos de dos columnas o mas

def calcularPopularidad(fila):
 resultado = fila["followees"]/fila["followers"]
 return resultado

df["popularidad"] = df.apply(calcularPopularidad, axis = 1) # Dado que estamos haciendo .apply() del DataFrame completo y no de una columna invidual, "axis = 1", le expecifica a metodo apply() que debe ser aplicado por cada fila del df.

df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees,ganancias,popularidad
id,,,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,ECUADOR,leonardokuffo,389.0,258,0.0,0.663239
183722,Today we commemorate and MNML Case.,500.0,21.0,-1.0,BRASIL,mateusmartins,982.0,1822,84.0,1.855397
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129,615.0,10.750000
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378,228.0,1.138554
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129,390.0,10.750000

### **Transformación agrupación o agregación**

Por ejemplo, en situaciones donde manejo datos categóricos, como el país, tengo la capacidad de organizar mis datos basándome en una categoría específica.

[Data Cleaning con Pandas. Part 1](https://medium.com/@patricrp/data-cleaning-con-pandas-parte-1-aaa681662b5d)

[Data Cleaning con Pandas. Part 2](https://medium.com/ironhack/data-cleaning-con-pandas-parte-2-a4e1f55e446b)

#### Sumar la información de otras columnas mediante la agregación. Por lo tanto calcular el promedio de "Me gustas" en los tweet por páis.

In [25]:
# AGRUPANDO Y AGREGANDO DATOS
# En recientes versiones de Pandas
# Tenemos que filtrar primero solo las columnas numericas y la columna por la que vamos a agrupar
df[
    ['country', 'favorites', 'retweets', 'mentions', 'followers', 'followees', 'ganancias', 'popularidad']
].groupby("country").mean() # Agrupando por pais y sacando la media de cada columna

,favorites,retweets,mentions,followers,followees,ganancias,popularidad
country,,,,,,,
BRASIL,339.909091,91.272727,17.727273,616.600,1889.363636,407.363636,3.708644
ECUADOR,186.375000,56.750000,11.875000,360.500,318.000000,208.125000,0.900897
MEXICO,294.857143,77.750000,13.750000,15.375,1101.000000,291.000000,55.308036

#### Agrupando por pais y aplicando diferentes funciones de agregacion a cada columna (followers: suma , mentions: media y retweets: maximo )

In [26]:
# Agrupando por pais y aplicando diferentes funciones de agregacion a cada columna
df.groupby("country").agg({
    "followers": 'sum',
    "mentions": 'mean',
    "retweets": 'max'
})

         followers   mentions  retweets
country
BRASIL      6166.0  17.727273     145.0
ECUADOR     2884.0  11.875000     146.0
MEXICO       123.0  13.750000     130.0

#### Crear un DataFrame llamado "grouped" que contenga la agrupación anterior

In [27]:
grouped = df.groupby("country").agg({
    "followers": 'sum',
    "mentions": 'mean',
    "retweets": 'max'
})

#### Filtrar los follower de DataFrame anterior donde sean mayores de 5000

In [28]:
grouped[grouped["followers"] > 5000]

         followers   mentions  retweets
country
BRASIL      6166.0  17.727273     145.0

#### Guardar nuestros datos transformados a CSV, JSON, SQL, ...

> Añadir blockquote

In [29]:
grouped.to_csv("/content/drive/MyDrive/CARLOS III 2023 2024/Colab Notebooks/Sistemas Big Data/grouped.csv")