# **Pandas en Python: Trabajando con Varios DataFrames y Fechas**

### **Importar librería**

In [ ]:
import pandas as pd

### **Cargar Varios DataFrames**

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Sistemas Big Data/01_dataset.csv")
df2 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Sistemas Big Data/02_dataset.csv")
df3 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Sistemas Big Data/03_dataset.csv")

### **Mostrar los 5 primeros elementos de los df**

In [ ]:
df1.head()

,id,full_text,favorites,retweets,mentions,user,fecha_publicado
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023

In [ ]:
df2.head()

        ciudad  followers  followees             user
0    GUAYAQUIL      389.0        258    leonardokuffo
1    SAO PAULO      982.0       1822    mateusmartins
2       OAXACA       12.0        129      pedrojuarez
3        QUITO      332.0        378     galocastillo
4  GUADALAJARA       21.0       2721  gabrielcarvajal

In [ ]:

df3.head()

           ciudad     pais
0       GUAYAQUIL  ECUADOR
1  RIO DE JANEIRO   BRASIL
2     GUADALAJARA   MEXICO
3          OAXACA   MEXICO
4           QUITO  ECUADOR

# **JOINS**
 Hacemos un Join para unir datos en dos datasets diferentes a partir de una columna

 [TODOS LOS TIPOS DE JOIN](https://ingenieriadesoftware.es/tipos-sql-join-guia-referencia/)

 [Doc Merge](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)

### **Unir el df1 con df2**

In [ ]:
df_con_df1_df2 = df1.merge(df2, on='user', how='left')
df_con_df1_df2.head()

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129

### **Unir el anterior Df con df3**

In [ ]:
df_final = df_con_df1_df2.merge(df3, on='ciudad', how='left')
df_final.head()

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO

### **Mostrar los tipos de dataframe**

In [ ]:
df_final.dtypes

id                   int64
full_text           object
favorites          float64
retweets           float64
mentions           float64
user                object
fecha_publicado     object
ciudad              object
followers          float64
followees            int64
pais                object
dtype: object

# **FECHAS**

[Doc Fechas](https://docs.python.org/es/3/library/datetime.html#strftime-and-strptime-format-codes)

### **Trasnformar a Fehca la columna fecha_publicado.**

Nota: Crear una columna fecha_pulblicacion_norm

In [ ]:
# Las fechas por defecto son cadenas de texto
# Con Python podemos trasformarlas a fechas
# Poseer las fechas en el formato de Fechas de Python facilita la reestructuración de las mismas o la organización del dataframe según esta columna.
df_final['fecha_pulblicacion_norm'] = pd.to_datetime(df_final['fecha_publicado'], format='%d/%m/%Y')
df_final.head()

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais,fecha_pulblicacion_norm
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-27
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-27
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR,2023-01-28
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28

### **Crear un columna con el dia de publicación**

In [ ]:
df_final['dia_semana'] = df_final['fecha_pulblicacion_norm'].apply(lambda x: x.strftime('%A'))
df_final.head()

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais,fecha_pulblicacion_norm,dia_semana
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-27,Friday
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-27,Friday
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR,2023-01-28,Saturday
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday

In [ ]:
#Ejempo usando funciones
def darDiaSemana(fecha):
  diaSemana = fecha.strftime('%A')
  return diaSemana

df_final['dia_semana_fun'] = df_final['fecha_pulblicacion_norm'].apply(darDiaSemana)
df_final.head()

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais,fecha_pulblicacion_norm,dia_semana,dia_semana_fun
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-27,Friday,Friday
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-27,Friday,Friday
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday,Saturday
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR,2023-01-28,Saturday,Saturday
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday,Saturday

### **Crear un columna con el mes y año de publicación**

In [ ]:
df_final['mes'] = df_final['fecha_pulblicacion_norm'].apply(lambda x: x.strftime('%m/%Y'))
df_final.head()

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais,fecha_pulblicacion_norm,dia_semana,dia_semana_fun,mes
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-27,Friday,Friday,01/2023
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-27,Friday,Friday,01/2023
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday,Saturday,01/2023
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR,2023-01-28,Saturday,Saturday,01/2023
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday,Saturday,01/2023

### **Sacar de la columna fecha_publicado el mes y año**

In [ ]:
df_final['mes'] = df_final['fecha_publicado'].apply(lambda x: x[3:])
df_final.head()

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais,fecha_pulblicacion_norm,dia_semana,dia_semana_fun,mes
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-27,Friday,Friday,01/2023
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-27,Friday,Friday,01/2023
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday,Saturday,01/2023
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR,2023-01-28,Saturday,Saturday,01/2023
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday,Saturday,01/2023

In [ ]:
# Usando funcion
def extraer_mes_y_anio_de_cadena(fecha_str):
    # Dividir la cadena por el carácter '/'
    partes = fecha_str.split('/')
    # El mes es el segundo elemento y el año es el tercer elemento
    mes = partes[1]
    anio = partes[2]
    # Devolver el mes y el año en el formato deseado
    return mes + '/' + anio
df_final['fecha_publicado'].apply(extraer_mes_y_anio_de_cadena)
df_final.head()

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais,fecha_pulblicacion_norm,dia_semana,dia_semana_fun,mes
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-27,Friday,Friday,01/2023
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-27,Friday,Friday,01/2023
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday,Saturday,01/2023
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR,2023-01-28,Saturday,Saturday,01/2023
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday,Saturday,01/2023

In [ ]:
# Funcion usando slice
def extraer_mes_y_anio_con_slice(fecha_str):
    # Extraer el mes y el año usando rebanada de string
    mes = fecha_str[3:5]
    anio = fecha_str[6:10]
    # Devolver el mes y el año en el formato deseado
    return mes + '/' + anio

df_final['fecha_publicado'].apply(extraer_mes_y_anio_con_slice)
df_final.head()

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais,fecha_pulblicacion_norm,dia_semana,dia_semana_fun,mes
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-27,Friday,Friday,01/2023
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-27,Friday,Friday,01/2023
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday,Saturday,01/2023
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR,2023-01-28,Saturday,Saturday,01/2023
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday,Saturday,01/2023

# **Guardar nuestros datos trasformados a CSV, JSON, SQL, ...**

In [ ]:
df_final.to_csv("/content/drive/MyDrive/Colab Notebooks/Sistemas Big Data/df_final.csv")